[package]

name = "lms_001"
version = "0.0.1"
authors = ["carlos rojas"]

[dependencies]
uuid="*"
serde_json="1.0"
serde_derive="1.0"
serde="1.0"
zmq="0.8.2"

[dependencies.postgres]
version="0.15"
features=["with-uuid", "with-serde_json"]
